import { IValidator } from '../../interface/validation/i-validator';
import { FormControl } from '@angular/forms';
import { IAccessableFormControl, IAccessableFormOptions } from '../../interface/validation/i-accessable-form-control';
import { Observable } from 'rxjs';
export declare class AccessableFormControl<TType = any> implements IAccessableFormControl<AccessableFormControl<TType>, TType> {
    control: FormControl;
    showAs: (value: any) => any;
    convertTo: (value: any) => any;
    private required$;
    private validators$;
    private blocked$;
    private previousValue$;
    initialize(formState?: any, validators?: IValidator[]): void;
    validateWith(validators?: IValidator[], opts?: IAccessableFormOptions): AccessableFormControl;
    setValue(value: any, skipSetPreviousValue?: boolean, opts?: IAccessableFormOptions): AccessableFormControl;
    reset(value: TType, skipSetPreviousValue?: boolean, opts?: IAccessableFormOptions): AccessableFormControl;
    markAsUsed(opts?: IAccessableFormOptions): AccessableFormControl;
    markAsUnused(opts?: IAccessableFormOptions): AccessableFormControl;
    markAsDirty(opts?: IAccessableFormOptions): AccessableFormControl;
    markAsTouched(opts?: IAccessableFormOptions): AccessableFormControl;
    disable(opts?: IAccessableFormOptions): AccessableFormControl;
    enable(opts?: IAccessableFormOptions): AccessableFormControl;
    blockControls(): void;
    unblockControls(): void;
    get disabled(): boolean;
    get valid(): boolean;
    get validators(): IValidator[];
    get error(): IValidator;
    get value(): any;
    set value(value: any);
    get valueChanges(): Observable<any>;
    get previousValue(): any;
    set previousValue(value: any);
    get required(): boolean;
    get touched(): boolean;
    get dirty(): boolean;
    get blocked(): boolean;
}
